#! /bin/sh
# ~/.profile
# --------------------------------------------------------------------------------
# Se estiver rodando bash
if [ -n "$BASH_VERSION" ]; then
    # Carrega o .bashrc se ele existir
    if [ -f "$HOME/.bashrc" ]; then
        source "$HOME/.bashrc"
    fi
fi
