#! /bin/sh
# ~/.bash_profile
# --------------------------------------------------------------------------------
# Carrega o .bashrc se ele existir
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi
